# Generated by Django 5.0.7 on 2024-07-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BusTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_name", models.CharField(max_length=100)),
                ("departure_time", models.TimeField()),
                ("arrival_time", models.TimeField()),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
            ],
        ),
    ]
